// -----------------------------------------------------------------------------------
// Comet <Programming Environment for Lua>
//      Copyright(C) 2010-2022 Pr. Sidi HAMADY
//      http://www.hamady.org
//      sidi@hamady.org
//
//      :STABLE:VERSION180:BUILD2104:
//
//      Released under the MIT licence (https://opensource.org/licenses/MIT)
//      See Copyright Notice in COPYRIGHT
// -----------------------------------------------------------------------------------


#ifndef IDENTIFIERS_H
#define IDENTIFIERS_H

// wxID_HIGHEST
#include <wx/defs.h>

#ifdef __WXMSW__
#include <winsock2.h>
#else
#include <unistd.h>
#include <netdb.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#endif

#define SIGMACALLER_EDITOR  1
#define SIGMACALLER_CONSOLE 2

#ifdef wxID_HIGHEST
#define ID_SIGMAFIRST (wxID_HIGHEST + 1)
#else
#define ID_SIGMAFIRST 6000
#endif

#define COMET_VERSION_NUMBER  186
#define COMET_BUILD_NUMBER    2104
#define COMET_VERSION_STRING  uT("1.8")
#define COMET_BUILD_STRING    uT("2104") // yymmdd (year, month, day)
#define COMET_BUILD_COPYRIGHT uT("(C) 2010-2022  Pr. Sidi HAMADY")
#define COMET_HEADER_STRING   uT("# Comet-RC <do not change or remove this header>")

#define ID_FIRST (ID_SIGMAFIRST + 100)

// Frame (100-1000)
#define ID_FILE              (ID_SIGMAFIRST + 100)
#define ID_FILE_NEW          (ID_SIGMAFIRST + 101)
#define ID_FILE_OPEN         (ID_SIGMAFIRST + 102)
#define ID_FILE_CLOSE        (ID_SIGMAFIRST + 103)
#define ID_FILE_SAVE         (ID_SIGMAFIRST + 104)
#define ID_FILE_SAVEAS       (ID_SIGMAFIRST + 105)
#define ID_FILE_SAVEALL      (ID_SIGMAFIRST + 106)
#define ID_FILE_FILELIST     (ID_SIGMAFIRST + 107)
#define ID_FILE_PRINT        (ID_SIGMAFIRST + 108)
#define ID_FILE_PRINTPREVIEW (ID_SIGMAFIRST + 109)

#define ID_FILE_RECENT (ID_SIGMAFIRST + 110)

// ID_FILE_RECENTxx order is mandatory
#define ID_FILE_RECENT_FIRST (ID_SIGMAFIRST + 111)
#define ID_FILE_RECENT01     ID_FILE_RECENT_FIRST
#define ID_FILE_RECENT02     (ID_SIGMAFIRST + 112)
#define ID_FILE_RECENT03     (ID_SIGMAFIRST + 113)
#define ID_FILE_RECENT04     (ID_SIGMAFIRST + 114)
#define ID_FILE_RECENT05     (ID_SIGMAFIRST + 115)
#define ID_FILE_RECENT06     (ID_SIGMAFIRST + 116)
#define ID_FILE_RECENT07     (ID_SIGMAFIRST + 117)
#define ID_FILE_RECENT08     (ID_SIGMAFIRST + 118)
#define ID_FILE_RECENT09     (ID_SIGMAFIRST + 119)
#define ID_FILE_RECENT10     (ID_SIGMAFIRST + 120)
#define ID_FILE_RECENT11     (ID_SIGMAFIRST + 121)
#define ID_FILE_RECENT12     (ID_SIGMAFIRST + 122)
#define ID_FILE_REOPEN       (ID_SIGMAFIRST + 123)
#define ID_FILE_RECENTCLEAR  (ID_SIGMAFIRST + 124)
#define ID_FILE_RECENT_LAST  ID_FILE_RECENTCLEAR
//

#define ID_FILE_CLOSEALL          (ID_SIGMAFIRST + 125)
#define ID_FILE_CLOSEOTHERS       (ID_SIGMAFIRST + 126)
#define ID_FILE_COPYPATH          (ID_SIGMAFIRST + 127)
#define ID_FILE_OPENDIR           (ID_SIGMAFIRST + 128)
#define ID_FILE_SETDIR            (ID_SIGMAFIRST + 129)
#define ID_FILE_OPENEXAMPLESDIR   (ID_SIGMAFIRST + 130)
#define ID_FILE_OPENSHELL         (ID_SIGMAFIRST + 131)
#define ID_FILE_FILEPROPS         (ID_SIGMAFIRST + 132)
#define ID_FILE_UPDATE            (ID_SIGMAFIRST + 133)
#define ID_FILE_NEWWINDOW         (ID_SIGMAFIRST + 134)
#define ID_FILE_FILESTATS         (ID_SIGMAFIRST + 135)
#define ID_FILE_READONLY          (ID_SIGMAFIRST + 136)
#define ID_FILE_DUPLICATE         (ID_SIGMAFIRST + 137)
#define ID_FILE_RESETMARKERS      (ID_SIGMAFIRST + 138)
#define ID_FILE_RESETMARKERSB     (ID_SIGMAFIRST + 139)
#define ID_FILE_REOPENLAST        (ID_SIGMAFIRST + 140)
#define ID_FILE_PIN               (ID_SIGMAFIRST + 141)
#define ID_FILE_CLOSEALLBUTPINNED (ID_SIGMAFIRST + 142)

// ID_FILE_LEXERxx order is mandatory
#define ID_FILE_LEXER01   (ID_SIGMAFIRST + 145)
#define ID_FILE_LEXER02   (ID_SIGMAFIRST + 146)
#define ID_FILE_LEXER03   (ID_SIGMAFIRST + 147)
#define ID_FILE_LEXER04   (ID_SIGMAFIRST + 148)
#define ID_FILE_LEXER05   (ID_SIGMAFIRST + 149)
#define ID_FILE_LEXER06   (ID_SIGMAFIRST + 150)
#define ID_FILE_LEXER07   (ID_SIGMAFIRST + 151)
#define ID_FILE_LEXER08   (ID_SIGMAFIRST + 152)
#define ID_FILE_LEXER09   (ID_SIGMAFIRST + 153)
#define ID_FILE_LEXER10   (ID_SIGMAFIRST + 154)
#define ID_FILE_LEXER11   (ID_SIGMAFIRST + 155)
#define ID_FILE_LEXER12   (ID_SIGMAFIRST + 156)
#define ID_FILE_LEXERLAST ID_FILE_LEXER12
//

#define ID_DIR_RECENT (ID_SIGMAFIRST + 160)

// ID_DIR_RECENTxx order is mandatory
#define ID_DIR_RECENT_FIRST (ID_SIGMAFIRST + 161)
#define ID_DIR_RECENT01     ID_DIR_RECENT_FIRST
#define ID_DIR_RECENT02     (ID_SIGMAFIRST + 162)
#define ID_DIR_RECENT03     (ID_SIGMAFIRST + 163)
#define ID_DIR_RECENT04     (ID_SIGMAFIRST + 164)
#define ID_DIR_RECENT05     (ID_SIGMAFIRST + 165)
#define ID_DIR_RECENT06     (ID_SIGMAFIRST + 166)
#define ID_DIR_RECENT07     (ID_SIGMAFIRST + 167)
#define ID_DIR_RECENT08     (ID_SIGMAFIRST + 168)
#define ID_DIR_RECENT09     (ID_SIGMAFIRST + 169)
#define ID_DIR_RECENT10     (ID_SIGMAFIRST + 170)
#define ID_DIR_RECENT11     (ID_SIGMAFIRST + 171)
#define ID_DIR_RECENT12     (ID_SIGMAFIRST + 172)
#define ID_DIR_RECENTCLEAR  (ID_SIGMAFIRST + 173)
#define ID_DIR_RECENT_LAST  ID_DIR_RECENTCLEAR
//

#define ID_FILE_EXIT (ID_SIGMAFIRST + 175)

#define ID_VIEW_EXPLORER  (ID_SIGMAFIRST + 180)
#define ID_VIEW_CONSOLE   (ID_SIGMAFIRST + 182)
#define ID_VIEW_OUTPUT    (ID_SIGMAFIRST + 183)
#define ID_VIEW_BOOKMARK  (ID_SIGMAFIRST + 184)
#define ID_VIEW_TOOLBAR   (ID_SIGMAFIRST + 185)
#define ID_VIEW_STATUSBAR (ID_SIGMAFIRST + 186)
#define ID_VIEW_SEARCHBAR (ID_SIGMAFIRST + 187)

#define ID_FILE_TEMPLATE01    (ID_SIGMAFIRST + 191)
#define ID_FILE_TEMPLATE02    (ID_SIGMAFIRST + 192)
#define ID_FILE_TEMPLATE02MOD (ID_SIGMAFIRST + 193)
#define ID_FILE_TEMPLATE03    (ID_SIGMAFIRST + 194)
#define ID_FILE_TEMPLATE04    (ID_SIGMAFIRST + 195)
#define ID_FILE_TEMPLATE05    (ID_SIGMAFIRST + 196)
#define ID_FILE_TEMPLATE06    (ID_SIGMAFIRST + 197)
#define ID_FILE_TEMPLATE07    (ID_SIGMAFIRST + 198)
#define ID_FILE_TEMPLATE08    (ID_SIGMAFIRST + 199)
#define ID_FILE_TEMPLATELAST  ID_FILE_TEMPLATE08

#define ID_TEMPLATE_C    ID_FILE_TEMPLATE02
#define ID_TEMPLATE_CMOD ID_FILE_TEMPLATE02MOD
#define ID_TEMPLATE_CPP  ID_FILE_TEMPLATE03

#define ID_CODE_SAMPLES (ID_SIGMAFIRST + 210)

#define ID_THREAD_CLEAR       (ID_SIGMAFIRST + 262)
#define ID_THREAD_PRINT       (ID_SIGMAFIRST + 263)
#define ID_THREAD_PRINTERR    (ID_SIGMAFIRST + 264)
#define ID_THREAD_BREAKPOINT  (ID_SIGMAFIRST + 265)
#define ID_THREAD_READ        (ID_SIGMAFIRST + 266)
#define ID_THREAD_STACK       (ID_SIGMAFIRST + 267)
#define ID_THREAD_MESSAGE     (ID_SIGMAFIRST + 278)
#define ID_THREAD_UPDATE      (ID_SIGMAFIRST + 279)
#define ID_THREAD_CURLINE     (ID_SIGMAFIRST + 280)
#define ID_THREAD_FINISH      (ID_SIGMAFIRST + 289)

#define ID_THREAD_CHECKUPDATE (ID_SIGMAFIRST + 291)

#define ID_SCRIPT_BRACEMATCH  (ID_SIGMAFIRST + 304)
#define ID_SCRIPT_PAGEACTIVE  (ID_SIGMAFIRST + 306)
#define ID_SCRIPT_LONGLINEON  (ID_SIGMAFIRST + 311)
#define ID_SCRIPT_OVERTYPE    (ID_SIGMAFIRST + 313)
#define ID_SCRIPT_READONLY    (ID_SIGMAFIRST + 314)
#define ID_SCRIPT_WRAPMODEON  (ID_SIGMAFIRST + 315)
#define ID_SCRIPT_CONVERTEOL  (ID_SIGMAFIRST + 316)
#define ID_SCRIPT_CONVERTCR   (ID_SIGMAFIRST + 317)
#define ID_SCRIPT_CONVERTCRLF (ID_SIGMAFIRST + 318)
#define ID_SCRIPT_CONVERTLF   (ID_SIGMAFIRST + 319)
#define ID_SCRIPT_STATUSBAR   (ID_SIGMAFIRST + 322)

#define ID_SCRIPT_START      (ID_SIGMAFIRST + 323)
#define ID_SCRIPT_STARTDEBUG (ID_SIGMAFIRST + 324)
#define ID_SCRIPT_STEPINTO   (ID_SIGMAFIRST + 325)
#define ID_SCRIPT_STOP       (ID_SIGMAFIRST + 326)

#define ID_SCRIPT_BREAKPOINT_MOD     (ID_SIGMAFIRST + 327)
#define ID_SCRIPT_BREAKPOINT_DELALL  (ID_SIGMAFIRST + 329)
#define ID_SCRIPT_COMMENTSELECTION   (ID_SIGMAFIRST + 341)
#define ID_SCRIPT_UNCOMMENTSELECTION (ID_SIGMAFIRST + 342)
#define ID_SCRIPT_UPPERCASE          (ID_SIGMAFIRST + 350)
#define ID_SCRIPT_LOWERCASE          (ID_SIGMAFIRST + 351)
#define ID_SCRIPT_FORMATDOC          (ID_SIGMAFIRST + 352)
#define ID_SCRIPT_KILLTOOL           (ID_SIGMAFIRST + 360)
#define ID_LATEX_TEXTBF              (ID_SIGMAFIRST + 363)
#define ID_LATEX_TEXTIT              (ID_SIGMAFIRST + 364)
#define ID_LATEX_TEXTSC              (ID_SIGMAFIRST + 365)
#define ID_LATEX_TEXTNORMAL          (ID_SIGMAFIRST + 366)
#define ID_LATEX_EMPH                (ID_SIGMAFIRST + 367)
#define ID_LATEX_TEXTSUPERSCRIPT     (ID_SIGMAFIRST + 368)
#define ID_LATEX_TEXTSUBSCRIPT       (ID_SIGMAFIRST + 369)
#define ID_LATEX_MATHRM              (ID_SIGMAFIRST + 370)
#define ID_CODE_FORMAT               (ID_SIGMAFIRST + 380)
#define ID_CODE_SNIPPET              (ID_SIGMAFIRST + 381)

#define IDD_SCRIPT_SAMPLES (ID_SIGMAFIRST + 401)
#define IDD_SCRIPT_CODE    (ID_SIGMAFIRST + 402)
#define ID_SCRIPT_LOAD     (ID_SIGMAFIRST + 403)

// ID_FILE_LISTxx order is mandatory
#define ID_FILE_LIST01   (ID_SIGMAFIRST + 411)
#define ID_FILE_LIST02   (ID_SIGMAFIRST + 412)
#define ID_FILE_LIST03   (ID_SIGMAFIRST + 413)
#define ID_FILE_LIST04   (ID_SIGMAFIRST + 414)
#define ID_FILE_LIST05   (ID_SIGMAFIRST + 415)
#define ID_FILE_LIST06   (ID_SIGMAFIRST + 416)
#define ID_FILE_LIST07   (ID_SIGMAFIRST + 417)
#define ID_FILE_LIST08   (ID_SIGMAFIRST + 418)
#define ID_FILE_LIST09   (ID_SIGMAFIRST + 419)
#define ID_FILE_LIST10   (ID_SIGMAFIRST + 420)
#define ID_FILE_LIST11   (ID_SIGMAFIRST + 421)
#define ID_FILE_LIST12   (ID_SIGMAFIRST + 422)
#define ID_FILE_LIST13   (ID_SIGMAFIRST + 423)
#define ID_FILE_LIST14   (ID_SIGMAFIRST + 424)
#define ID_FILE_LIST15   (ID_SIGMAFIRST + 425)
#define ID_FILE_LIST16   (ID_SIGMAFIRST + 426)
#define ID_FILE_LIST17   (ID_SIGMAFIRST + 427)
#define ID_FILE_LIST18   (ID_SIGMAFIRST + 428)
#define ID_FILE_LIST19   (ID_SIGMAFIRST + 429)
#define ID_FILE_LIST20   (ID_SIGMAFIRST + 430)
#define ID_FILE_LIST21   (ID_SIGMAFIRST + 431)
#define ID_FILE_LIST22   (ID_SIGMAFIRST + 432)
#define ID_FILE_LIST23   (ID_SIGMAFIRST + 433)
#define ID_FILE_LIST24   (ID_SIGMAFIRST + 434)
#define ID_FILE_LIST25   (ID_SIGMAFIRST + 435)
#define ID_FILE_LIST26   (ID_SIGMAFIRST + 436)
#define ID_FILE_LIST27   (ID_SIGMAFIRST + 437)
#define ID_FILE_LIST28   (ID_SIGMAFIRST + 438)
#define ID_FILE_LIST29   (ID_SIGMAFIRST + 439)
#define ID_FILE_LIST30   (ID_SIGMAFIRST + 440)
#define ID_FILE_LIST31   (ID_SIGMAFIRST + 441)
#define ID_FILE_LIST32   (ID_SIGMAFIRST + 442)
#define ID_FILE_LIST33   (ID_SIGMAFIRST + 443)
#define ID_FILE_LIST34   (ID_SIGMAFIRST + 444)
#define ID_FILE_LIST35   (ID_SIGMAFIRST + 445)
#define ID_FILE_LIST36   (ID_SIGMAFIRST + 446)
#define ID_FILE_LIST37   (ID_SIGMAFIRST + 447)
#define ID_FILE_LIST38   (ID_SIGMAFIRST + 448)
#define ID_FILE_LIST39   (ID_SIGMAFIRST + 449)
#define ID_FILE_LIST40   (ID_SIGMAFIRST + 450)
#define ID_FILE_LIST41   (ID_SIGMAFIRST + 451)
#define ID_FILE_LIST42   (ID_SIGMAFIRST + 452)
#define ID_FILE_LIST43   (ID_SIGMAFIRST + 453)
#define ID_FILE_LIST44   (ID_SIGMAFIRST + 454)
#define ID_FILE_LIST45   (ID_SIGMAFIRST + 455)
#define ID_FILE_LIST46   (ID_SIGMAFIRST + 456)
#define ID_FILE_LIST47   (ID_SIGMAFIRST + 457)
#define ID_FILE_LIST48   (ID_SIGMAFIRST + 458)
#define ID_FILE_LIST49   (ID_SIGMAFIRST + 459)
#define ID_FILE_LIST50   (ID_SIGMAFIRST + 460)
#define ID_FILE_LIST51   (ID_SIGMAFIRST + 461)
#define ID_FILE_LIST52   (ID_SIGMAFIRST + 462)
#define ID_FILE_LIST53   (ID_SIGMAFIRST + 463)
#define ID_FILE_LIST54   (ID_SIGMAFIRST + 464)
#define ID_FILE_LIST55   (ID_SIGMAFIRST + 465)
#define ID_FILE_LIST56   (ID_SIGMAFIRST + 466)
#define ID_FILE_LIST57   (ID_SIGMAFIRST + 467)
#define ID_FILE_LIST58   (ID_SIGMAFIRST + 468)
#define ID_FILE_LIST59   (ID_SIGMAFIRST + 469)
#define ID_FILE_LIST60   (ID_SIGMAFIRST + 470)
#define ID_FILE_LIST61   (ID_SIGMAFIRST + 471)
#define ID_FILE_LIST62   (ID_SIGMAFIRST + 472)
#define ID_FILE_LIST63   (ID_SIGMAFIRST + 473)
#define ID_FILE_LIST64   (ID_SIGMAFIRST + 474)
#define ID_FILE_LISTLAST (ID_SIGMAFIRST + 474)
//

#define IDD_TOAST      (ID_SIGMAFIRST + 501)
#define IDL_TOAST      (ID_SIGMAFIRST + 502)
#define ID_TOAST_TIMER (ID_SIGMAFIRST + 503)

#define IDD_DISP (ID_SIGMAFIRST + 510)

#define IDD_PLOT (ID_SIGMAFIRST + 520)

#define ID_SEARCH_FIND           (ID_SIGMAFIRST + 600)
#define ID_SEARCH_REPLACE        (ID_SIGMAFIRST + 601)
#define ID_SEARCH_FINDINFILES    (ID_SIGMAFIRST + 602)
#define ID_SEARCH_REPLACEINFILES (ID_SIGMAFIRST + 603)
#define ID_SEARCH_RESETMARKERS   (ID_SIGMAFIRST + 604)
#define ID_SEARCH_GOTO           (ID_SIGMAFIRST + 605)
#define ID_SCRIPT_COLORS         (ID_SIGMAFIRST + 607)
#define ID_SCRIPT_LEXER          (ID_SIGMAFIRST + 610)

#define ID_SCRIPT_BOOKMARK_MOD        (ID_SIGMAFIRST + 611)
#define ID_SCRIPT_BOOKMARK_DELALL     (ID_SIGMAFIRST + 612)
#define ID_SCRIPT_BOOKMARK_NEXT       (ID_SIGMAFIRST + 613)
#define ID_SCRIPT_BOOKMARK_PREV       (ID_SIGMAFIRST + 614)
#define ID_SCRIPT_BOOKMARK_LIST       (ID_SIGMAFIRST + 615)
#define ID_SCRIPT_BOOKMARK_LIST_FIRST (ID_SIGMAFIRST + 616)
#define ID_SCRIPT_BOOKMARK_LIST_LAST  (ID_SIGMAFIRST + 679)

#define ID_SCRIPT_INFOBAR_NEXTM (ID_SIGMAFIRST + 682)
#define ID_SCRIPT_INFOBAR_PREVM (ID_SIGMAFIRST + 683)
#define ID_SCRIPT_INFOBAR_NEXTS (ID_SIGMAFIRST + 684)
#define ID_SCRIPT_INFOBAR_PREVS (ID_SIGMAFIRST + 685)
#define ID_SCRIPT_INFOBAR_NEXTF (ID_SIGMAFIRST + 686)
#define ID_SCRIPT_INFOBAR_PREVF (ID_SIGMAFIRST + 687)
#define ID_SCRIPT_INFOBAR_NEXTK (ID_SIGMAFIRST + 688)
#define ID_SCRIPT_INFOBAR_PREVK (ID_SIGMAFIRST + 689)
#define ID_SCRIPT_INFOBAR_NEXTE (ID_SIGMAFIRST + 690)
#define ID_SCRIPT_INFOBAR_PREVE (ID_SIGMAFIRST + 691)
#define ID_SCRIPT_INFOBAR_NEXTD (ID_SIGMAFIRST + 692)
#define ID_SCRIPT_INFOBAR_PREVD (ID_SIGMAFIRST + 693)
#define ID_SCRIPT_INFOBAR_NEXTB (ID_SIGMAFIRST + 694)
#define ID_SCRIPT_INFOBAR_PREVB (ID_SIGMAFIRST + 695)
#define ID_SCRIPT_INFOBAR_NEXTX (ID_SIGMAFIRST + 698)
#define ID_SCRIPT_INFOBAR_PREVX (ID_SIGMAFIRST + 699)

// Continuous ID from first to last
#define ID_SCRIPT_OPTION_FIRST   (ID_SIGMAFIRST + 718)
#define ID_SCRIPT_SYNTAX         (ID_SIGMAFIRST + 719)
#define ID_SCRIPT_AUTOCOMPLETE   (ID_SIGMAFIRST + 720)
#define ID_SCRIPT_CALLTIP        (ID_SIGMAFIRST + 721)
#define ID_SCRIPT_LINENUMBERS    (ID_SIGMAFIRST + 722)
#define ID_SCRIPT_MARGINMARKERS  (ID_SIGMAFIRST + 723)
#define ID_SCRIPT_MARGINSTATUS   (ID_SIGMAFIRST + 724)
#define ID_SCRIPT_FOLDENABLE     (ID_SIGMAFIRST + 725)
#define ID_SCRIPT_WRAPMODE       (ID_SIGMAFIRST + 726)
#define ID_SCRIPT_DETECTCHANGE   (ID_SIGMAFIRST + 727)
#define ID_SCRIPT_DISPLAYEOL     (ID_SIGMAFIRST + 728)
#define ID_SCRIPT_WHITESPACE     (ID_SIGMAFIRST + 729)
#define ID_SCRIPT_LONGLINE       (ID_SIGMAFIRST + 730)
#define ID_SCRIPT_SAVENAVIGATION (ID_SIGMAFIRST + 731)
#define ID_SCRIPT_VIEWINFOBAR    (ID_SIGMAFIRST + 732)
#define ID_SCRIPT_OPTION_LAST    (ID_SIGMAFIRST + 732)
//

#define ID_SCRIPT_ZOOMIN          (ID_SIGMAFIRST + 733)
#define ID_SCRIPT_ZOOMOUT         (ID_SIGMAFIRST + 734)
#define ID_SCRIPT_ZOOMNONE        (ID_SIGMAFIRST + 735)
#define ID_SCRIPT_LINESPACING_100 (ID_SIGMAFIRST + 736)
#define ID_SCRIPT_LINESPACING_125 (ID_SIGMAFIRST + 737)
#define ID_SCRIPT_LINESPACING_150 (ID_SIGMAFIRST + 738)
#define ID_SCRIPT_LINESPACING_175 (ID_SIGMAFIRST + 739)
#define ID_SCRIPT_THEME           (ID_SIGMAFIRST + 745)

#define ID_TOOLS_BUILD  (ID_SIGMAFIRST + 760)

#define IDD_INPUT            (ID_SIGMAFIRST + 901)
#define IDL_INPUT            (ID_SIGMAFIRST + 902)
#define IDE_INPUT            (ID_SIGMAFIRST + 903)
#define ID_HELP_CONTENTS_PDF (ID_SIGMAFIRST + 997)
#define ID_HELP_CHECKUPDATE  (ID_SIGMAFIRST + 998)
#define ID_HELP_ABOUT        (ID_SIGMAFIRST + 999)

#define ID_THREAD_OUTPUT_SET    (ID_SIGMAFIRST + 1001)
#define ID_THREAD_OUTPUT_APPEND (ID_SIGMAFIRST + 1002)
#define ID_THREAD_OUTPUT_CLEAR  (ID_SIGMAFIRST + 1009)

// ColorsDlg (2600-2700)
#define IDD_SCRIPT_COLORS            (ID_SIGMAFIRST + 2601)
#define ID_SCRIPT_COLOR_DEF          (ID_SIGMAFIRST + 2602)
#define ID_SCRIPT_COLOR_KEY          (ID_SIGMAFIRST + 2603)
#define ID_SCRIPT_COLOR_STR          (ID_SIGMAFIRST + 2604)
#define ID_SCRIPT_COLOR_COM          (ID_SIGMAFIRST + 2605)
#define ID_SCRIPT_COLOR_NUM          (ID_SIGMAFIRST + 2606)
#define ID_SCRIPT_COLOR_LIB          (ID_SIGMAFIRST + 2607)
#define ID_SCRIPT_COLOR_PREPROCESSOR (ID_SIGMAFIRST + 2608)
#define ID_SCRIPT_COLOR_IDENTIFIER   (ID_SIGMAFIRST + 2609)
#define ID_SCRIPT_COLOR_LINENUM      (ID_SIGMAFIRST + 2611)
#define ID_SCRIPT_COLOR_LINENUMBACK  (ID_SIGMAFIRST + 2612)
#define ID_SCRIPT_COLOR_DEFBACK      (ID_SIGMAFIRST + 2613)
#define ID_SCRIPT_COLOR_CARETBACK    (ID_SIGMAFIRST + 2614)
#define ID_SCRIPT_COLOR_SELBACK      (ID_SIGMAFIRST + 2615)
#define ID_SCRIPT_COLOR_WSBACK       (ID_SIGMAFIRST + 2616)
#define ID_SCRIPT_COLOR_MARKMOD      (ID_SIGMAFIRST + 2617)
#define ID_SCRIPT_COLOR_MARKSAVED    (ID_SIGMAFIRST + 2618)
#define ID_SCRIPT_COLOR_MARKFIND     (ID_SIGMAFIRST + 2619)
#define ID_SCRIPT_COLOR_MARKERROR    (ID_SIGMAFIRST + 2620)

#define IDK_SCRIPT_FONTSTYLE_DEF     (ID_SIGMAFIRST + 2621)
#define IDK_SCRIPT_FONTSTYLE_KEY     (ID_SIGMAFIRST + 2622)
#define IDK_SCRIPT_FONTSTYLE_STR     (ID_SIGMAFIRST + 2623)
#define IDK_SCRIPT_FONTSTYLE_COM     (ID_SIGMAFIRST + 2624)
#define IDK_SCRIPT_FONTSTYLE_NUM     (ID_SIGMAFIRST + 2625)
#define IDK_SCRIPT_FONTSTYLE_LIB     (ID_SIGMAFIRST + 2626)
#define IDK_SCRIPT_FONTSTYLE_PREPROC (ID_SIGMAFIRST + 2627)
#define IDK_SCRIPT_FONTSTYLE_IDENT   (ID_SIGMAFIRST + 2628)
#define IDK_SCRIPT_FONTSTYLE_LINENUM (ID_SIGMAFIRST + 2629)

#define IDL_SCRIPT_FONTSTYLE_DEF         (ID_SIGMAFIRST + 2631)
#define IDL_SCRIPT_FONTSTYLE_KEY         (ID_SIGMAFIRST + 2632)
#define IDL_SCRIPT_FONTSTYLE_STR         (ID_SIGMAFIRST + 2633)
#define IDL_SCRIPT_FONTSTYLE_COM         (ID_SIGMAFIRST + 2634)
#define IDL_SCRIPT_FONTSTYLE_NUM         (ID_SIGMAFIRST + 2635)
#define IDL_SCRIPT_FONTSTYLE_LIB         (ID_SIGMAFIRST + 2636)
#define IDL_SCRIPT_FONTSTYLE_LINENUM     (ID_SIGMAFIRST + 2637)
#define IDL_SCRIPT_FONTSTYLE_LINENUMBACK (ID_SIGMAFIRST + 2638)
#define IDL_SCRIPT_FONTSTYLE_DEFBACK     (ID_SIGMAFIRST + 2639)
#define IDL_SCRIPT_FONTSTYLE_CARETBACK   (ID_SIGMAFIRST + 2640)

#define ID_NOTEBOOK_FILESYS (ID_SIGMAFIRST + 2686)
#define ID_NOTEBOOK_MAIN    (ID_SIGMAFIRST + 2687)
#define ID_NOTEBOOK_TOOLBOX (ID_SIGMAFIRST + 2688)
#define ID_NOTEBOOK_DEBUG   (ID_SIGMAFIRST + 2689)

#define IDL_DEBUG_WATCH (ID_SIGMAFIRST + 2691)
#define IDL_DEBUG_STACK (ID_SIGMAFIRST + 2692)

#define ID_SCRIPT_EXAMPLE_FIRST (ID_SIGMAFIRST + 2701)
#define ID_SCRIPT_EXAMPLE_01    ID_SCRIPT_EXAMPLE_FIRST
#define ID_SCRIPT_EXAMPLE_02    (ID_SIGMAFIRST + 2702)
#define ID_SCRIPT_EXAMPLE_03    (ID_SIGMAFIRST + 2703)
#define ID_SCRIPT_EXAMPLE_04    (ID_SIGMAFIRST + 2704)
#define ID_SCRIPT_EXAMPLE_05    (ID_SIGMAFIRST + 2705)
#define ID_SCRIPT_EXAMPLE_06    (ID_SIGMAFIRST + 2706)
#define ID_SCRIPT_EXAMPLE_07    (ID_SIGMAFIRST + 2707)
#define ID_SCRIPT_EXAMPLE_08    (ID_SIGMAFIRST + 2708)
#define ID_SCRIPT_EXAMPLE_LAST  ID_SCRIPT_EXAMPLE_08

#define ID_SCRIPT_SNIPPET_FIRST    (ID_SIGMAFIRST + 2731)
#define ID_SCRIPT_SNIPPET_01       ID_SCRIPT_SNIPPET_FIRST
#define ID_SCRIPT_SNIPPET_02       (ID_SIGMAFIRST + 2732)
#define ID_SCRIPT_SNIPPET_03       (ID_SIGMAFIRST + 2733)
#define ID_SCRIPT_SNIPPET_04       (ID_SIGMAFIRST + 2734)
#define ID_SCRIPT_SNIPPET_05       (ID_SIGMAFIRST + 2735)
#define ID_SCRIPT_SNIPPET_06       (ID_SIGMAFIRST + 2736)
#define ID_SCRIPT_SNIPPET_07       (ID_SIGMAFIRST + 2737)
#define ID_SCRIPT_SNIPPET_08       (ID_SIGMAFIRST + 2738)
#define ID_SCRIPT_SNIPPET_09       (ID_SIGMAFIRST + 2739)
#define ID_SCRIPT_SNIPPET_10       (ID_SIGMAFIRST + 2740)
#define ID_SCRIPT_SNIPPET_11       (ID_SIGMAFIRST + 2741)
#define ID_SCRIPT_SNIPPET_12       (ID_SIGMAFIRST + 2742)
#define ID_SCRIPT_SNIPPET_13       (ID_SIGMAFIRST + 2743)
#define ID_SCRIPT_SNIPPET_14       (ID_SIGMAFIRST + 2744)
#define ID_SCRIPT_SNIPPET_15       (ID_SIGMAFIRST + 2745)
#define ID_SCRIPT_SNIPPET_16       (ID_SIGMAFIRST + 2746)
#define ID_SCRIPT_SNIPPET_17       (ID_SIGMAFIRST + 2747)
#define ID_SCRIPT_SNIPPET_18       (ID_SIGMAFIRST + 2748)
#define ID_SCRIPT_SNIPPET_19       (ID_SIGMAFIRST + 2749)
#define ID_SCRIPT_SNIPPET_20       (ID_SIGMAFIRST + 2750)
#define ID_SCRIPT_SNIPPET_21       (ID_SIGMAFIRST + 2751)
#define ID_SCRIPT_SNIPPET_LAST     ID_SCRIPT_SNIPPET_21
#define ID_SCRIPT_SNIPPET_LASTMENU ID_SCRIPT_SNIPPET_12

// TabDlg (2750-2800)
#define ID_SCRIPT_INDENT           (ID_SIGMAFIRST + 2770)
#define IDD_SCRIPT_INDENT          (ID_SIGMAFIRST + 2771)
#define ID_SCRIPT_INDENTOPT        (ID_SIGMAFIRST + 2772)
#define ID_SCRIPT_INDENTSIZE       (ID_SIGMAFIRST + 2773)
#define ID_SCRIPT_INDENTGUIDE      (ID_SIGMAFIRST + 2774)
#define IDK_SCRIPT_LONGLINE        (ID_SIGMAFIRST + 2775)
#define IDE_SCRIPT_LONGLINE_COLUMN (ID_SIGMAFIRST + 2776)

// LinePropertiesDlg (3000-3100)
#define IDD_GEOMETRIC_LINE (ID_SIGMAFIRST + 3001)
#define IDO_ARROW_BEGIN    (ID_SIGMAFIRST + 3002)
#define IDO_ARROW_END      (ID_SIGMAFIRST + 3003)
#define IDO_ARROW_BOTH     (ID_SIGMAFIRST + 3004)
#define IDO_ARROW_NONE     (ID_SIGMAFIRST + 3005)
#define IDO_ARROW_STYLE00  (ID_SIGMAFIRST + 3006)
#define IDO_ARROW_STYLE01  (ID_SIGMAFIRST + 3007)

// LinePropertiesDlg (3100-3200)
#define IDD_GEOMETRIC_RECT (ID_SIGMAFIRST + 3101)
#define IDC_FILL_COLOR     (ID_SIGMAFIRST + 3102)
#define IDK_FILL           (ID_SIGMAFIRST + 3103)

// TextDlg (3300-3400)
#define IDD_TEXT           (ID_SIGMAFIRST + 3301)
#define IDC_TEXT_FONTCOLOR (ID_SIGMAFIRST + 3302)
#define ID_TEXT_FONTCHOOSE (ID_SIGMAFIRST + 3303)
#define IDO_TEXT_ORIENT00  (ID_SIGMAFIRST + 3304)
#define IDO_TEXT_ORIENT90  (ID_SIGMAFIRST + 3305)
#define IDO_TEXT_ORIENT270 (ID_SIGMAFIRST + 3306)

// FindDirDlg (3400-3500)
#define IDD_FIND           (ID_SIGMAFIRST + 3401)
#define IDE_FIND_WHAT      (ID_SIGMAFIRST + 3402)
#define IDE_FIND_REPLACE   (ID_SIGMAFIRST + 3403)
#define IDE_FIND_TYPE      (ID_SIGMAFIRST + 3404)
#define IDO_FIND_WHERE     (ID_SIGMAFIRST + 3405)
#define IDE_FIND_DIR       (ID_SIGMAFIRST + 3406)
#define IDK_FIND_SUBDIR    (ID_SIGMAFIRST + 3407)
#define ID_FIND_BROWSEDIR  (ID_SIGMAFIRST + 3408)
#define IDK_FIND_CASE      (ID_SIGMAFIRST + 3409)
#define IDK_FIND_WORD      (ID_SIGMAFIRST + 3410)
#define IDK_FIND_REGEXP    (ID_SIGMAFIRST + 3411)
#define ID_FIND_PREV       (ID_SIGMAFIRST + 3412)
#define ID_FIND_NEXT       (ID_SIGMAFIRST + 3413)
#define ID_FIND_FINDALL    (ID_SIGMAFIRST + 3414)
#define ID_FIND_REPLACE    (ID_SIGMAFIRST + 3415)
#define ID_FIND_REPLACEALL (ID_SIGMAFIRST + 3416)
#define IDL_FIND_RESULT    (ID_SIGMAFIRST + 3417)
#define ID_FIND_DELETE     (ID_SIGMAFIRST + 3418)
#define ID_FIND_DELETEALL  (ID_SIGMAFIRST + 3419)
#define ID_FIND_GOTO       (ID_SIGMAFIRST + 3420)
#define ID_FIND_CLOSE      (ID_SIGMAFIRST + 3429)
#define IDK_FIND_MARKER    (ID_SIGMAFIRST + 3430)
#define IDK_FIND_CYCLIC    (ID_SIGMAFIRST + 3431)
#define IDD_FINDDIR        (ID_SIGMAFIRST + 3441)

// BookmarkDlg (3500-3580)
#define IDD_BOOKMARK          (ID_SIGMAFIRST + 3501)
#define IDL_BOOKMARK          (ID_SIGMAFIRST + 3502)
#define ID_BOOKMARK_GOTO      (ID_SIGMAFIRST + 3503)
#define ID_BOOKMARK_DELETE    (ID_SIGMAFIRST + 3504)
#define ID_BOOKMARK_DELETEALL (ID_SIGMAFIRST + 3505)
#define ID_BOOKMARK_REFRESH   (ID_SIGMAFIRST + 3506)
#define ID_BOOKMARK_CLOSE     (ID_SIGMAFIRST + 3510)

// ToolsDlg (3580-3600)
#define IDD_TOOLS      (ID_SIGMAFIRST + 3581)
#define IDE_TOOLS_TYPE (ID_SIGMAFIRST + 3582)
#define IDE_TOOLS_CMD  (ID_SIGMAFIRST + 3583)
#define IDE_TOOLS_OUT  (ID_SIGMAFIRST + 3584)
#define IDE_TOOLS_LOG  (ID_SIGMAFIRST + 3585)
#if defined(__WXGTK__)
#define IDE_TOOLS_TERM  (ID_SIGMAFIRST + 3586)
#define IDE_TOOLS_OPT   (ID_SIGMAFIRST + 3587)
#define IDE_TOOLS_SHELL (ID_SIGMAFIRST + 3588)
#endif
#define IDK_TOOLS_KEEPTERM (ID_SIGMAFIRST + 3589)
#define IDE_TOOLS_CLS      (ID_SIGMAFIRST + 3590)

// FileStatsDlg (3600-3620)
#define IDD_SCRIPT_STATS (ID_SIGMAFIRST + 3601)

// LexerDlg (3660-3680)
#define IDD_LEXER          (ID_SIGMAFIRST + 3661)
#define IDE_LEXER_PATTERN  (ID_SIGMAFIRST + 3662)
#define IDE_LEXER_KEYWORDS (ID_SIGMAFIRST + 3663)
#define ID_LEXER_LOAD      (ID_SIGMAFIRST + 3665)
#define ID_LEXER_SAVE      (ID_SIGMAFIRST + 3666)
#define ID_LEXER_CLOSE     (ID_SIGMAFIRST + 3679)

#define ID_FILE_RELOAD (ID_SIGMAFIRST + 4001)

// Window ID
#define ID_WINDOW_EDITORPANEL     (ID_SIGMAFIRST + 4010)
#define ID_WINDOW_CONSOLEPANEL    (ID_SIGMAFIRST + 4020)
#define ID_WINDOW_OUTPUTPANEL     (ID_SIGMAFIRST + 4030)
#define ID_WINDOW_INFOBAR         (ID_SIGMAFIRST + 4040)
#define ID_WINDOW_INFOBAR_CONSOLE (ID_SIGMAFIRST + 4050)
#define ID_WINDOW_INFOBAR_OUTPUT  (ID_SIGMAFIRST + 4060)
#define ID_WINDOW_MAIN            (ID_SIGMAFIRST + 5000)
#define ID_WINDOW_SCRIPT          (ID_SIGMAFIRST + 5100)
#define ID_WINDOW_CONSOLE         (ID_SIGMAFIRST + 5200)
#define ID_WINDOW_OUTPUT          (ID_SIGMAFIRST + 5300)

#define ID_MAIN_FIRST              (ID_SIGMAFIRST + 5005)
#define ID_MAIN_SELECTWORD         (ID_SIGMAFIRST + 5005)
#define ID_MAIN_SELECTLINE         (ID_SIGMAFIRST + 5006)
#define ID_MAIN_UNDO               (ID_SIGMAFIRST + 5007)
#define ID_MAIN_REDO               (ID_SIGMAFIRST + 5008)
#define ID_MAIN_INSERT_DATE        (ID_SIGMAFIRST + 5009)
#define ID_MAIN_INSERT_TIME        (ID_SIGMAFIRST + 5010)
#define ID_MAIN_INSERT_DATETIME    (ID_SIGMAFIRST + 5011)
#define ID_MAIN_INDENTINC          (ID_SIGMAFIRST + 5012)
#define ID_MAIN_INDENTDEC          (ID_SIGMAFIRST + 5013)
#define ID_MAIN_FONT               (ID_SIGMAFIRST + 5014)
#define ID_MAIN_UTF8FROM_ISO8859L1 (ID_SIGMAFIRST + 5015)
#define ID_MAIN_UTF8FROM_ISO8859L9 (ID_SIGMAFIRST + 5016)
#define ID_MAIN_UTF8FROM_CP1252    (ID_SIGMAFIRST + 5017)
#define ID_MAIN_ANALYZE            (ID_SIGMAFIRST + 5018)
#define ID_MAIN_LAST               (ID_SIGMAFIRST + 5018)

#define ID_MAIN_GOTO (ID_SIGMAFIRST + 5074)

#define ID_SCRIPT_FIRST              (ID_SIGMAFIRST + 5105)
#define ID_SCRIPT_SELECTWORD         (ID_SIGMAFIRST + 5105)
#define ID_SCRIPT_SELECTLINE         (ID_SIGMAFIRST + 5106)
#define ID_SCRIPT_UNDO               (ID_SIGMAFIRST + 5107)
#define ID_SCRIPT_REDO               (ID_SIGMAFIRST + 5108)
#define ID_SCRIPT_INSERT_DATE        (ID_SIGMAFIRST + 5109)
#define ID_SCRIPT_INSERT_TIME        (ID_SIGMAFIRST + 5110)
#define ID_SCRIPT_INSERT_DATETIME    (ID_SIGMAFIRST + 5111)
#define ID_SCRIPT_INDENTINC          (ID_SIGMAFIRST + 5112)
#define ID_SCRIPT_INDENTDEC          (ID_SIGMAFIRST + 5113)
#define ID_SCRIPT_FONT               (ID_SIGMAFIRST + 5114)
#define ID_SCRIPT_UTF8FROM_ISO8859L1 (ID_SIGMAFIRST + 5115)
#define ID_SCRIPT_UTF8FROM_ISO8859L9 (ID_SIGMAFIRST + 5116)
#define ID_SCRIPT_UTF8FROM_CP1252    (ID_SIGMAFIRST + 5117)
#define ID_SCRIPT_ANALYZE            (ID_SIGMAFIRST + 5118)
#define ID_SCRIPT_LAST               (ID_SIGMAFIRST + 5118)

#define ID_CONSOLE_FIRST        (ID_SIGMAFIRST + 5205)
#define ID_CONSOLE_SELECTWORD   (ID_SIGMAFIRST + 5205)
#define ID_CONSOLE_SELECTLINE   (ID_SIGMAFIRST + 5206)
#define ID_CONSOLE_UNDO         (ID_SIGMAFIRST + 5207)
#define ID_CONSOLE_REDO         (ID_SIGMAFIRST + 5208)
#define ID_CONSOLE_RUN          (ID_SIGMAFIRST + 5209)
#define ID_CONSOLE_STOP         (ID_SIGMAFIRST + 5210)
#define ID_CONSOLE_ZOOMIN       (ID_SIGMAFIRST + 5211)
#define ID_CONSOLE_ZOOMOUT      (ID_SIGMAFIRST + 5212)
#define ID_CONSOLE_ZOOMNONE     (ID_SIGMAFIRST + 5213)
#define ID_CONSOLE_SYNTAX       (ID_SIGMAFIRST + 5214)
#define ID_CONSOLE_AUTOCOMPLETE (ID_SIGMAFIRST + 5215)
#define ID_CONSOLE_CALLTIP      (ID_SIGMAFIRST + 5216)
#define ID_CONSOLE_RESET        (ID_SIGMAFIRST + 5217)
#define ID_CONSOLE_LAST         (ID_SIGMAFIRST + 5217)

#define ID_OUTPUT_FIRST      (ID_SIGMAFIRST + 5305)
#define ID_OUTPUT_SELECTWORD (ID_SIGMAFIRST + 5305)
#define ID_OUTPUT_SELECTLINE (ID_SIGMAFIRST + 5306)
#define ID_OUTPUT_UNDO       (ID_SIGMAFIRST + 5307)
#define ID_OUTPUT_REDO       (ID_SIGMAFIRST + 5308)
#define ID_OUTPUT_ZOOMIN     (ID_SIGMAFIRST + 5309)
#define ID_OUTPUT_ZOOMOUT    (ID_SIGMAFIRST + 5310)
#define ID_OUTPUT_ZOOMNONE   (ID_SIGMAFIRST + 5311)
#define ID_OUTPUT_CLEARKEY   (ID_SIGMAFIRST + 5312)
#define ID_OUTPUT_LAST       (ID_SIGMAFIRST + 5312)
#define ID_OUTPUT_RESET      (ID_SIGMAFIRST + 5319)

#define IDC_EXPLORER           (ID_SIGMAFIRST + 5401)
#define ID_EXPLORER_REFRESH    (ID_SIGMAFIRST + 5402)
#define ID_EXPLORER_BROWSE     (ID_SIGMAFIRST + 5403)
#define ID_EXPLORER_OPEN       (ID_SIGMAFIRST + 5404)
#define ID_EXPLORER_OPENEXT    (ID_SIGMAFIRST + 5405)
#define ID_EXPLORER_COPYPATH   (ID_SIGMAFIRST + 5406)
#define ID_EXPLORER_OPENSHELL  (ID_SIGMAFIRST + 5407)
#define ID_EXPLORER_FILEPROPS  (ID_SIGMAFIRST + 5408)
#define ID_EXPLORER_CREATEFILE (ID_SIGMAFIRST + 5409)
#define ID_EXPLORER_CREATEDIR  (ID_SIGMAFIRST + 5410)
#define ID_EXPLORER_RENAME     (ID_SIGMAFIRST + 5411)
#define ID_EXPLORER_CUT        (ID_SIGMAFIRST + 5412)
#define ID_EXPLORER_COPY       (ID_SIGMAFIRST + 5413)
#define ID_EXPLORER_PASTE      (ID_SIGMAFIRST + 5414)
#define ID_EXPLORER_DELETE     (ID_SIGMAFIRST + 5415)
#define ID_EXPLORER_CHANGEDIR  (ID_SIGMAFIRST + 5421)

#define ID_VIEW_TRANSPARENCY (ID_SIGMAFIRST + 5504)
#define ID_VIEW_TOPMOST      (ID_SIGMAFIRST + 5505)
#define ID_VIEW_RESETUI      (ID_SIGMAFIRST + 5506)

#define IDC_ANALYZE_LIST (ID_SIGMAFIRST + 5601)
#define ID_ANALYZE_GOTO  (ID_SIGMAFIRST + 5602)
#define ID_ANALYZE_RESET (ID_SIGMAFIRST + 5611)
#define ID_INCLUDE_GOTO  (ID_SIGMAFIRST + 5612)

#define TIMER_ID_SIGMAFRAME        (ID_SIGMAFIRST + 8901)
#define TIMER_ID_SCRIPTEDIT        (ID_SIGMAFIRST + 8902)
#define TIMER_ID_FINDDIR           (ID_SIGMAFIRST + 8903)
#define TIMER_ID_SCRIPTEDIT_RELOAD (ID_SIGMAFIRST + 8904)

// Common (9800-9999)
#define ID_APPLY     (ID_SIGMAFIRST + 9801)
#define ID_OK        (ID_SIGMAFIRST + 9802)
#define ID_CANCEL    (ID_SIGMAFIRST + 9803)
#define ID_COPY      (ID_SIGMAFIRST + 9804)
#define ID_UNDO      (ID_SIGMAFIRST + 9805)
#define ID_NOTHING   (ID_SIGMAFIRST + 9995)
#define ID_CLOSE     (ID_SIGMAFIRST + 9996)
#define ID_VERSION   (ID_SIGMAFIRST + 9997)
#define IDD_ABOUTBOX (ID_SIGMAFIRST + 9998)
#define IDC_STATIC   (ID_SIGMAFIRST + 9999)

#define ID_LAST (ID_SIGMAFIRST + 9999)

#include "../etc/app_small.xpm"

#include "../etc/filenew_small.xpm"
#include "../etc/fileopen_small.xpm"
#include "../etc/fileopen_disabled_small.xpm"
#include "../etc/filesave_small.xpm"
#include "../etc/filesaveas_small.xpm"
#include "../etc/filesaveall_small.xpm"
#include "../etc/filesave_disabled_small.xpm"
#include "../etc/filesaveall_disabled_small.xpm"
#include "../etc/filelist_small.xpm"

#include "../etc/print_small.xpm"

#include "../etc/output_small.xpm"
#include "../etc/console_small.xpm"
#include "../etc/prompt_small.xpm"

#include "../etc/copy_small.xpm"
#include "../etc/cut_small.xpm"
#include "../etc/paste_small.xpm"
#include "../etc/undo_small.xpm"
#include "../etc/redo_small.xpm"
#include "../etc/clear_small.xpm"
#include "../etc/lf_small.xpm"
#include "../etc/indentinc_small.xpm"
#include "../etc/indentdec_small.xpm"
#include "../etc/selectall_small.xpm"
#include "../etc/insertdate_small.xpm"
#include "../etc/format_small.xpm"

#include "../etc/toolmenu_small.xpm"

#include "../etc/zoomin_small.xpm"
#include "../etc/zoomout_small.xpm"

#include "../etc/find_small.xpm"
#include "../etc/find_next_small.xpm"
#include "../etc/find_prev_small.xpm"
#include "../etc/find_files_small.xpm"

#include "../etc/marker_next_small.xpm"
#include "../etc/marker_prev_small.xpm"

#include "../etc/snippet_small.xpm"
#include "../etc/code_small.xpm"

#include "../etc/autoreload_small.xpm"

#include "../etc/reset_small.xpm"

#include "../etc/start_small.xpm"
#include "../etc/stop_small.xpm"
#include "../etc/pause_small.xpm"
#include "../etc/startdebug_small.xpm"

#include "../etc/breakpoint_small.xpm"
#include "../etc/breakpoint_add_small.xpm"

#include "../etc/bookmark_small.xpm"
#include "../etc/bookmark_add_small.xpm"
#include "../etc/bookmark_next_small.xpm"
#include "../etc/bookmark_prev_small.xpm"
#include "../etc/bookmark_deleteall_small.xpm"
#include "../etc/bookmarkdlg_small.xpm"

#include "../etc/started_small.xpm"
#include "../etc/starteddebug_small.xpm"
#include "../etc/startedx_small.xpm"
#include "../etc/error_small.xpm"

#include "../etc/debug_small.xpm"
#include "../etc/stack_small.xpm"

#include "../etc/colors_small.xpm"
#include "../etc/linespacing100_small.xpm"
#include "../etc/linespacing175_small.xpm"

#include "../etc/folder_small.xpm"
#include "../etc/folder_disabled_small.xpm"
#include "../etc/comment_small.xpm"
#include "../etc/uncomment_small.xpm"

#include "../etc/lua_small.xpm"

#include "../etc/iso8859l1_small.xpm"
#include "../etc/iso8859l9_small.xpm"

#include "../etc/readonly_small.xpm"

#include "../etc/analyze_small.xpm"
#include "../etc/analyze_goto_small.xpm"

#include "../etc/bookmark_list_small.xpm"

#include "../etc/findin_small.xpm"
#include "../etc/modified_small.xpm"
#include "../etc/pinned_small.xpm"

#include "../etc/none_small.xpm"

#include "../etc/quit_small.xpm"

#define COMET_MAXFILES 64

#define MAINFRAME_SIZEW 900
#define MAINFRAME_SIZEH 675

#define SCRIPT_DEFAULT_TITLE uT("Script")

#define SCRIPT_NEWLINE uT("\n")

#define OUTPUT_MAXLINES 256

#endif
